In [2]:
import json
import pennylane as qml
import pennylane.numpy as np
from pennylane.math import *
import scipy
import numpy

from math import pi

from qiskit import QuantumCircuit, QuantumRegister, ClassicalRegister, 
# from 

#### **TimBit**

In [3]:
U_NP = [[1, 0, 0, 0], [0, 0, 0, 1], [0, 1, 0, 0], [0, 0, 1, 0]]

def calculate_timbit(U, rho_0, rho, n_iters):
    """
    This function will return a timbit associated to the operator U and a state passed as an attribute.

    Args:
        U (numpy.tensor): A 2-qubit gate in matrix form.
        rho_0 (numpy.tensor): The matrix of the input density matrix.
        rho (numpy.tensor): A guess at the fixed point C[rho] = rho.
        n_iters (int): The number of iterations of C.

    Returns:
        (tuple(numpy.tensor)): The fixed point density matrices.
    """

    rho_two = np.tensor( numpy.kron( rho_0.unwrap(), rho.unwrap() ) )

    evolved_rho_two = np.dot( U  , np.dot(rho_two, U.transpose() ) )

    return reduced_dm(evolved_rho_two, [0])


In [ ]:
calculate_timbit(u, )

In [13]:
u = np.tensor(U_NP)

a = np.tensor([[1,0],[0,1]])
b = np.tensor([[1,2],[2,1]])

In [20]:
reduced_dm(u, [0])

tensor([[1.+0.j, 1.+0.j],
        [0.+0.j, 0.+0.j]], requires_grad=True)

In [5]:
s = tensordot(a,b, axes= 0)

In [9]:
a.unwrap(), b.unwrap()

(array([[1, 0],
        [0, 1]]),
 array([[1, 2],
        [2, 1]]))

In [36]:
u.dot(s)

ValueError: shapes (4,4) and (2,2,2,2) not aligned: 4 (dim 1) != 2 (dim 2)

In [12]:
np.tensor(numpy.kron(a.unwrap(), b.unwrap()))

tensor([[1, 2, 0, 0],
        [2, 1, 0, 0],
        [0, 0, 1, 2],
        [0, 0, 2, 1]], requires_grad=True)

#### **FalseProof**

In [19]:
import json
import pennylane as qml
import pennylane.numpy as np

# dev = qml.device("default.qubit", wires=2, shots=1)
# dev.operations.add("op")
# dev.operations.add("C(op)")

In [26]:
import json
import pennylane as qml
import pennylane.numpy as np

dev = qml.device("default.qubit", wires=2, shots=1)
dev.operations.add("op")
dev.operations.add("C(op)")


@qml.qnode(dev)
def circuit(U):
    """This will be the circuit you will use to determine which of the two angles we have.
    Remember that only a single shot will be executed.

    Args:
        U (qml.ops): It is the gate to discriminate between  RY(2pi/3) or RY(4pi/3).

    Returns:
        (numpy.tensor): Vector of two elements representing the output measured in each of the qubits.
    """
    # Put your code here #
    # to use U,  call 'U(wires = <wire where you want to apply the gate>)'
    # to use Control-U, call 'qml.ctrl(U, control = <control wire>)(wires = <wire where you want to apply the gate>)'
    return qml.sample(wires=range(2))

def process_output(measurement):
    """This function processes the output of the circuit to discriminate between gates.

    Args:
        measurement (numpy.array): Output of the previous circuit a vector of dimension 2.

    Returns:
        (int): return 2 or 4 depending on the associated RY gate.
    """
    # Put your code here #


# These functions are responsible for testing the solution.
def run(test_case_input: str) -> str:
    return None

def check(solution_output: str, expected_output: str) -> None:
    numbers = 2 * np.random.randint(1, 3, 5000)

    def U2(wires):
        class op(qml.operation.Operator):
            num_wires = 1

            def compute_decomposition(self, wires):
                raise ValueError("You cannot decompose this gate")

            def matrix(self):
                return qml.matrix(qml.RY(2 * np.pi / 3, wires=3))

        op(wires=wires)
        return None

    def U4(wires):
        class op(qml.operation.Operator):
            num_wires = 1

            def compute_decomposition(self, wires):
                raise ValueError("You cannot decompose this gate")

            def matrix(self):
                return qml.matrix(qml.RY(4 * np.pi / 3, wires=3))

        op(wires=wires)
        return None

    output = []
    for i in numbers:
        if i == 2:
            U = U2
        else:
            U = U4
        out = circuit(U)
        output.append(process_output(out))

    assert np.allclose(
        output, numbers, rtol=1e-4
    ), "Your circuit does not give the correct output."


test_cases = [['No input', 'No output']]

for i, (input_, expected_output) in enumerate(test_cases):
    print(f"Running test case {i} with input '{input_}'...")

    try:
        output = run(input_)

    except Exception as exc:
        print(f"Runtime Error. {exc}")

    else:
        if message := check(output, expected_output):
            print(f"Wrong Answer. Have: '{output}'. Want: '{expected_output}'.")

        else:
            print("Correct!")

VersionConflict: (numpy 1.24.2 (/usr/local/lib/python3.10/dist-packages), Requirement.parse('numpy<1.24'))

In [22]:
def U2(wires):
        class op(qml.operation.Operator):
            num_wires = 1

            def compute_decomposition(self, wires):
                raise ValueError("You cannot decompose this gate")

            def matrix(self):
                return qml.matrix(qml.RY(2 * np.pi / 3, wires=3))

        op(wires=wires)
        return None

In [24]:
circuit(U2)

NameError: name 'circuit' is not defined

In [7]:
from qiskit.circuit.library import RYGate

In [15]:
a = RYGate(2*pi/3).to_matrix(); b = RYGate(4*pi/3).to_matrix()

In [17]:
a

array([[ 0.5      +0.j, -0.8660254+0.j],
       [ 0.8660254+0.j,  0.5      +0.j]])

In [18]:
b

array([[-0.5      +0.j, -0.8660254+0.j],
       [ 0.8660254+0.j, -0.5      +0.j]])

In [16]:
numpy.linalg.eig(a), numpy.linalg.eig(b)

((array([0.5+0.8660254j, 0.5-0.8660254j]),
  array([[ 7.07106781e-01+0.j        ,  7.07106781e-01+0.j        ],
         [-0.00000000e+00-0.70710678j, -2.22044605e-16+0.70710678j]])),
 (array([-0.5+0.8660254j, -0.5-0.8660254j]),
  array([[ 0.70710678+0.j        ,  0.        -0.70710678j],
         [-0.        -0.70710678j,  0.70710678+0.j        ]])))

In [36]:
nrm = np.abs(1 + numpy.exp( 4j* pi / 3)) +  np.abs(1 - numpy.exp( 4j* pi / 3))

np.abs(1 + numpy.exp( 4j* pi / 3)) / nrm,  np.abs(1 - numpy.exp( 4j* pi / 3)) / nrm

(0.3660254037844385, 0.6339745962155615)

1j

#### **Desperate Measures**

In [13]:
from qiskit.circuit import Parameter
from qiskit.compiler import transpiler, transpile
basic_g = ['ry', 'rz', 'rx', 'cx']
jz = Parameter('jz');jx = Parameter('jx');jy = Parameter('jy')

In [93]:
jz/2

ParameterExpression(jz/2)

In [102]:
qc = QuantumCircuit(4)
for trtr in range(1):
    for i in range(4):
        qc.rxx(jx, i,(i+1)%4)
    # qc.barrier()
    # for i in range(4):
        qc.ryy(jy, i,(i+1)%4)
    # qc.barrier()
    # for i in range(4):
        qc.rzz(jz, i,(i+1)%4)

        

In [103]:
qc.draw(), qc.num_nonlocal_gates(), qc.decompose().num_nonlocal_gates()

(     ┌──────────┐┌──────────┐                                          »
 q_0: ┤0         ├┤0         ├─■────────────────────────────────────────»
      │  Rxx(jx) ││  Ryy(jy) │ │ZZ(jz) ┌──────────┐┌──────────┐         »
 q_1: ┤1         ├┤1         ├─■───────┤0         ├┤0         ├─■───────»
      └──────────┘└──────────┘         │  Rxx(jx) ││  Ryy(jy) │ │ZZ(jz) »
 q_2: ─────────────────────────────────┤1         ├┤1         ├─■───────»
                                       └──────────┘└──────────┘         »
 q_3: ──────────────────────────────────────────────────────────────────»
                                                                        »
 «                                      ┌──────────┐┌──────────┐         
 «q_0: ─────────────────────────────────┤1         ├┤1         ├─■───────
 «                                      │          ││          │ │       
 «q_1: ─────────────────────────────────┤          ├┤          ├─┼───────
 «     ┌──────────┐┌──────────┐       

In [104]:
qc_trns = transpile(qc, basis_gates= basic_g, optimization_level= 3)
qc_trns.draw(output= 'text'), qc_trns.num_nonlocal_gates()

(     ┌─────────┐┌───────┐                    ┌──────────┐┌─────────┐     »
 q_0: ┤ Ry(π/2) ├┤ Rx(π) ├──■──────────────■──┤ Rz(-π/2) ├┤ Ry(π/2) ├──■──»
      ├─────────┤├───────┤┌─┴─┐┌────────┐┌─┴─┐├──────────┤├─────────┤┌─┴─┐»
 q_1: ┤ Ry(π/2) ├┤ Rx(π) ├┤ X ├┤ Rz(jx) ├┤ X ├┤ Rz(-π/2) ├┤ Ry(π/2) ├┤ X ├»
      ├─────────┤├───────┤└───┘└────────┘└───┘└──────────┘└─────────┘└───┘»
 q_2: ┤ Ry(π/2) ├┤ Rx(π) ├────────────────────────────────────────────────»
      ├─────────┤├───────┤                                                »
 q_3: ┤ Ry(π/2) ├┤ Rx(π) ├────────────────────────────────────────────────»
      └─────────┘└───────┘                                                »
 «     ┌──────────┐┌──────────┐     ┌─────────┐     ┌─────────┐┌───────┐     »
 «q_0: ┤ Ry(-π/2) ├┤ Rz(-π/2) ├──■──┤ Ry(π/2) ├──■──┤ Ry(π/2) ├┤ Rx(π) ├─────»
 «     └┬────────┬┘└┬────────┬┘┌─┴─┐└┬────────┤┌─┴─┐├─────────┤├───────┤     »
 «q_1: ─┤ Rz(jy) ├──┤ Rx(-π) ├─┤ X ├─┤ Rz(jz) ├┤ X ├┤ Ry(π/2) ├┤ Rx(π) ├──■──»


In [65]:
# qc_trns.qasm(True)

In [ ]:
num_wires = 4
dev = qml.device("default.mixed", wires=num_wires)

@qml.qnode(dev)
def heisenberg_trotter(couplings, p, time, depth):
    """This QNode returns the final state of the spin chain after evolution for a time t, 
    under the Trotter approximation of the exponential of the Heisenberg Hamiltonian.
    
    Args:
        couplings (list(float)): 
            An array of length 4 that contains the coupling constants and the magnetic field 
            strength, in the order [J_x, J_y, J_z, h].
        p (float): The depolarization probability after each CNOT gate.
        depth (int): The Trotterization depth.
        time (float): Time during which the state evolves

    Returns:
        (numpy.tensor): The evolved quantum state.

    """
    jx = couplings[0]; jy = couplings[1]; jz = couplings[2]; h = couplings[3]
    for i in range(4):
        qml.RY( np.pi /2 , wires= i)
        qml.RX(np.pi, wires= i)
    for i in range(4):
        qml.CNOT(wires= [i, (i+1)%4])
        qml.RZ(jx, wires= [(i+1)%4])
        qml.CNOT(wires= [i, (i+1)%4])
    for i in range(4):
        qml.RY( np.pi /2 , wires= i)
        qml.RX(np.pi, wires= i)

    for i in range(4):
        qml.RX(np.pi/2, wires= [i])
    for i in range(4):
        qml.CNOT(wires= [i, (i+1)%4])
        qml.RZ(jy, wires= [(i+1)%4])
        qml.CNOT(wires= [i, (i+1)%4])
    for i in range(4):
        qml.RX(-1 * np.pi/2, wires= [i])

    for i in range(4):
        qml.CNOT(wires= [i, (i+1)%4])
        qml.RZ(jz, wires= [(i+1)%4])
        qml.CNOT(wires= [i, (i+1)%4])
    